version: '3'
services:
  web:
    image: nginx
    hostname: swag_sym_web
    container_name: swag_sym_web
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "9900:80"
    restart: always
    depends_on:
      - php

  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: symfony:818-local
    restart: always
    hostname: swag_sym_php
    container_name: swag_sym_php
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html

  db:
    image: postgres:14
    restart: always
    hostname: swag_sym_db
    container_name: swag_sym_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5990:5432"
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
