# Expose your documentation as JSON swagger compliant
#app.swagger:
#    path: /swagger/doc.json
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /swagger/api
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
